import * as pthread_api from '../bindings/duckdb-coi.pthread';
import DuckDB from '../bindings/duckdb-coi';
import { BROWSER_RUNTIME, prepareHTTPRangeBroker } from '../bindings/runtime_browser';

// Register the global DuckDB runtime.
globalThis.DUCKDB_RUNTIME = {};
for (const func of Object.getOwnPropertyNames(BROWSER_RUNTIME)) {
    if (func === 'constructor') continue;
    globalThis.DUCKDB_RUNTIME[func] = Object.getOwnPropertyDescriptor(BROWSER_RUNTIME, func)!.value;
}

// Temporary bounded diagnostics. Do not fake `loaded` or alter the pthread pool.
const traceStartup = (workerID: number, stage: string): void => {
    if (workerID !== 1) return;
    postMessage({ cmd: `coi-startup-worker-1:${stage}` });
};

// Match the load protocol generated by the pinned Emscripten 3.1.57 worker.
const generatedOnMessage = pthread_api.onmessage;
const handleMessage = (event: MessageEvent<any>): void => {
    const data = event.data;
    if (data.cmd === 'load') {
        traceStartup(data.workerID, 'load-received');
        const queued: MessageEvent<any>[] = [];
        globalThis.onmessage = (next: MessageEvent<any>) => queued.push(next);
        const module = pthread_api.getModule();
        module['wasmModule'] = data.wasmModule;
        module['sharedModules'] = data.sharedModules;
        module['wasmMemory'] = data.wasmMemory;
        module['buffer'] = data.wasmMemory.buffer;
        module['workerID'] = data.workerID;
        module['ENVIRONMENT_IS_PTHREAD'] = true;
        for (const handler of data.handlers || []) {
            module[handler] = (...args: any[]) => postMessage({ cmd: 'callHandler', handler, args });
        }
        // This is the original generated worker's synchronous WebAssembly.Instance
        // callback. Trace its entry, completion and receiveInstance separately to
        // distinguish CPU contention from module setup and dylink initialization.
        if (data.workerID === 1) {
            const generatedInstantiate = module['instantiateWasm'];
            if (typeof generatedInstantiate !== 'function') {
                traceStartup(data.workerID, 'instantiateWasm-missing');
            } else {
                module['instantiateWasm'] = (imports: any, receiveInstance: any) => {
                    traceStartup(data.workerID, 'instantiateWasm-enter');
                    try {
                        const result = generatedInstantiate(imports, (instance: any, wasmModule: any) => {
                            traceStartup(data.workerID, 'receiveInstance-enter');
                            const exports = receiveInstance(instance, wasmModule);
                            traceStartup(data.workerID, 'receiveInstance-returned');
                            return exports;
                        });
                        traceStartup(data.workerID, 'instantiateWasm-returned');
                        return result;
                    } catch (error) {
                        traceStartup(data.workerID, 'instantiateWasm-threw');
                        throw error;
                    }
                };
            }
        }
        (globalThis as any).startWorker = (instance: any) => {
            traceStartup(data.workerID, 'startWorker-entered');
            pthread_api.setModule(instance);
            // Prewarm the nested async-fetch helper before Emscripten marks this
            // pthread ready. readFile() later blocks with Atomics.wait(), so
            // creating the helper lazily at first read can deadlock its startup.
            prepareHTTPRangeBroker().then(() => {
                traceStartup(data.workerID, 'range-broker-ready');
                postMessage({ cmd: 'loaded' });
                traceStartup(data.workerID, 'loaded-posted');
                globalThis.onmessage = handleMessage;
                for (const pending of queued) handleMessage(pending);
            }).catch((error: unknown) => {
                traceStartup(data.workerID, 'range-broker-failed');
                console.error('[coi pthread] range broker initialization failed', data.workerID, error);
                throw error;
            });
        };
        try {
            traceStartup(data.workerID, 'duckdb-factory-enter');
            DuckDB(module).then(() => {
                traceStartup(data.workerID, 'duckdb-factory-resolved');
            }).catch((error: unknown) => {
                traceStartup(data.workerID, 'duckdb-factory-rejected');
                console.error('[coi pthread] module initialization failed', data.workerID, error);
                throw error;
            });
            traceStartup(data.workerID, 'duckdb-factory-returned');
        } catch (error) {
            traceStartup(data.workerID, 'duckdb-factory-threw');
            console.error('[coi pthread] module initialization threw', data.workerID, error);
            throw error;
        }
    } else if (data.cmd === 'registerFileHandle') {
        globalThis.DUCKDB_RUNTIME._files = globalThis.DUCKDB_RUNTIME._files || new Map();
        globalThis.DUCKDB_RUNTIME._files.set(data.fileName, data.fileHandle);
    } else if (data.cmd === 'dropFileHandle') {
        globalThis.DUCKDB_RUNTIME._files = globalThis.DUCKDB_RUNTIME._files || new Map();
        globalThis.DUCKDB_RUNTIME._files.delete(data.fileName);
    } else if (data.cmd === 'registerUDFFunction') {
        globalThis.DUCKDB_RUNTIME._udfFunctions = globalThis.DUCKDB_RUNTIME._udfFunctions || new Map();
        globalThis.DUCKDB_RUNTIME._udfFunctions.set(data.udf.name, data.udf);
    } else if (data.cmd === 'dropUDFFunctions') {
        globalThis.DUCKDB_RUNTIME._udfFunctions = globalThis.DUCKDB_RUNTIME._udfFunctions || new Map();
        for (const key of globalThis.DUCKDB_RUNTIME._udfFunctions.keys()) {
            if (globalThis.DUCKDB_RUNTIME._udfFunctions.get(key).connection_id === data.connectionId) {
                globalThis.DUCKDB_RUNTIME._udfFunctions.delete(key);
            }
        }
    } else {
        generatedOnMessage(event);
    }
};
globalThis.onmessage = handleMessage;
